use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    tauri_build::build();
    embed_default_map_caches();
}

/// Generate a static table that embeds every default-mod MapCache BIG
/// (public/mods/default/rts/map-caches/locations/*.big) directly into the
/// executable, so a fresh portable_data can be repopulated offline.
fn embed_default_map_caches() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let caches_dir = manifest
        .join("..")
        .join("public")
        .join("mods")
        .join("default")
        .join("rts")
        .join("map-caches")
        .join("locations");
    println!("cargo:rerun-if-changed={}", caches_dir.display());
    let mut ids: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&caches_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let is_big = path
                .extension()
                .and_then(|value| value.to_str())
                .map(|value| value.eq_ignore_ascii_case("big"))
                .unwrap_or(false);
            if !is_big {
                continue;
            }
            if let Some(stem) = path.file_stem().and_then(|value| value.to_str()) {
                if stem.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-') {
                    ids.push(stem.to_string());
                }
            }
        }
    }
    ids.sort();
    let mut source = String::from(
        "// AUTO-GENERATED by build.rs — embedded default-mod MapCache BIGs.\n\
         // Source of truth: public/mods/default/rts/map-caches/locations/.\n\
         pub static EMBEDDED_MAP_CACHES: &[(&str, &[u8])] = &[\n",
    );
    for id in &ids {
        let path = caches_dir.join(format!("{id}.big"));
        let absolute = fs::canonicalize(&path).unwrap_or(path);
        source.push_str(&format!(
            "    (\"{id}\", include_bytes!({absolute:?})),\n"
        ));
    }
    source.push_str("];\n");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set"));
    let destination = out_dir.join("embedded_map_caches.rs");
    if fs::read_to_string(&destination).ok().as_deref() != Some(source.as_str()) {
        fs::write(&destination, source).expect("failed to write embedded_map_caches.rs");
    }
}
