#!/usr/bin/env python3
"""
Генератор .big-файла с AddModule для спавна войск (ТЕСТОВЫЙ, одиночный отряд).

Создаёт отдельный big-патч, добавляющий к объекту WOTRTemporaryVictoryAnchor
один модуль ObjectCreationUpgrade. Для полного состава армии (несколько
отрядов + авторасстановка) используй bridge/spawn.py через main.py.

Запуск:
    python tools\\big_make.py --unit GondorArcherHorde
    python tools\\big_make.py --unit GondorFighterHorde --out C:\\RotWK\\__wotr_generated_presets.big
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from bridge import spawn as _spawn

DEFAULT_BIG = _spawn.SPAWN_BIG_DEFAULT
INTERNAL_PATH = _spawn.SPAWN_INTERNAL_PATH
OBJECT_NAME = "WOTRTemporaryVictoryAnchor"
MODULE_TAG = "ModuleTag_SpawnHorde"
FOURCC = b"BIGF"


def _ini_content(unit):
    return (
        "; spawn horde (generated by big_make.py)\n"
        f"Object {OBJECT_NAME}\n"
        "    AddModule\n"
        f"        Behavior = ObjectCreationUpgrade {MODULE_TAG}\n"
        "            TriggeredBy       = Upgrade_AllFactionUpgrade\n"
        f"            ThingToSpawn      = {unit}\n"
        "        End\n"
        "    End\n"
        "End\n"
    ).encode("latin-1")


def main(argv=None):
    ap = argparse.ArgumentParser(description="создать .big-патч спавна (один отряд)")
    ap.add_argument("--unit", required=True,
                    help="имя отряда (horde), напр. GondorArcherHorde")
    ap.add_argument("--out", default=DEFAULT_BIG, help="путь выходного .big")
    ap.add_argument("--fourcc", default="BIGF", choices=["BIG4", "BIGF"],
                    help="сигнатура архива (по умолчанию BIGF)")
    args = ap.parse_args(argv)

    ini = _ini_content(args.unit)
    big = _spawn.build_big(args.fourcc.encode("latin-1"), [(INTERNAL_PATH, ini)])

    with open(args.out, "wb") as f:
        f.write(big)

    print(f"[big_make] создан {args.out}")
    print(f"[big_make]   внутри: {INTERNAL_PATH} ({len(ini)} байт)")
    print(f"[big_make]   размер архива: {len(big)} байт, сигнатура {args.fourcc}")
    print()
    print("Содержимое ini:")
    print(ini.decode("latin-1"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
